### ISSUE TITLE
Type-Only Imports make an error

### ISSUE THREAD

**Issue by 5ouma** [ocavue/astrobook#66]
When I import only types from `.astro` files to the `.stories.ts`, it outputs an error and doesn't start.

```
Unexpected token (1:23)
  Stack trace:
    at pp$4.raise (node_modules/acorn/dist/acorn.mjs:3640:13)
    at pp$9.expect (node_modules/acorn/dist/acorn.mjs:760:26)
    at pp$8.parseImport (node_modules/acorn/dist/acorn.mjs:1845:28)
    at pp$8.parseTopLevel (node_modules/acorn/dist/acorn.mjs:823:21)
    at Function.parse (node_modules/acorn/dist/acorn.mjs:645:35)
error: script "astrobook" exited with code 1
```

**Comment by MicheMayer** [comment]
The problem is the acorn parser used during the consumption of story files.
It is only equipped to handle jsx. So an explicit type import or type syntax will cause a syntax error.

See here:
https://github.com/ocavue/astrobook/blob/535b85c3ac34f1eb4302bbcef445af0ec01a5816/packages/core/src/utils/get-exports.ts#L1-L14

The only way to fix this is to transpile typescript first before consuming it or use a different parser.
As a quick fix you could avoid using that syntax and configure your project with:
`tsconfig.json`
```json
{
  "verbatimModuleSyntax": false,
}
```

**Comment by jorgearuv** [comment]
Any plans to support TS files for stories?

**Comment by altano** [comment]
This means the example from [the quick start](https://github.com/ocavue/astrobook?tab=readme-ov-file) doesn't work, right?

**Comment by northstarthemes** [comment]
> This means the example from [the quick start](https://github.com/ocavue/astrobook?tab=readme-ov-file) doesn't work, right?

Right, so I [forked this repo](https://github.com/northstarthemes/astrobook) to resolve this issue
